import Header from '../components/Header';
import Head from 'next/head'
import HomeContent from '../components/Home/home';
import ProductScreen from '../components/Products/productScreen';
import HelpScreen from '../components/Help/HelpScreen';
import ContactScreen from '../components/Contact/ContactScreen';
import AboutScreen from '../components/About/AboutScreen';

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Rotas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
      <HomeContent />
      <ProductScreen />
      <HelpScreen />
      <ContactScreen />
      <AboutScreen />
    </>
  )
}
