import styles from '../Home/styles.module.css';

export default function Home() {
    return (
        <section id='home' className={styles.section}>
            <h1>Home</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat corporis sit non quas ipsa minima esse iste, saepe officiis sequi magni? Voluptate at voluptatem, temporibus assumenda atque obcaecati non voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis a vero nulla nostrum optio modi eveniet impedit, neque, aut nobis dolor rerum! Minus eos fuga sapiente omnis, itaque dolores hic! Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi officia accusantium hic quasi fuga a illo temporibus. Delectus harum vitae distinctio similique accusantium, aliquam, molestias deleniti, sunt modi repellendus reprehenderit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro, est provident totam libero ullam nihil deleniti velit enim iste? Quod ex expedita officia, minima nesciunt ut sapiente deserunt laborum iusto? Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor provident in fugit tenetur adipisci sequi incidunt, eius eaque fuga quas ducimus magni natus dignissimos officia, quisquam asperiores ut ratione qui.</p>
            <h1>Título 2</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat corporis sit non quas ipsa minima esse iste, saepe officiis sequi magni? Voluptate at voluptatem, temporibus assumenda atque obcaecati non voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis a vero nulla nostrum optio modi eveniet impedit, neque, aut nobis dolor rerum! Minus eos fuga sapiente omnis, itaque dolores hic! Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi officia accusantium hic quasi fuga a illo temporibus. Delectus harum vitae distinctio similique accusantium, aliquam, molestias deleniti, sunt modi repellendus reprehenderit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro, est provident totam libero ullam nihil deleniti velit enim iste? Quod ex expedita officia, minima nesciunt ut sapiente deserunt laborum iusto? Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor provident in fugit tenetur adipisci sequi incidunt, eius eaque fuga quas ducimus magni natus dignissimos officia, quisquam asperiores ut ratione qui.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellat corporis sit non quas ipsa minima esse iste, saepe officiis sequi magni? Voluptate at voluptatem, temporibus assumenda atque obcaecati non voluptatum. Lorem ipsum dolor sit amet consectetur adipisicing elit. Veritatis a vero nulla nostrum optio modi eveniet impedit, neque, aut nobis dolor rerum! Minus eos fuga sapiente omnis, itaque dolores hic! Lorem ipsum dolor sit amet consectetur adipisicing elit. Excepturi officia accusantium hic quasi fuga a illo temporibus. Delectus harum vitae distinctio similique accusantium, aliquam, molestias deleniti, sunt modi repellendus reprehenderit! Lorem ipsum dolor sit amet consectetur adipisicing elit. Porro, est provident totam libero ullam nihil deleniti velit enim iste? Quod ex expedita officia, minima nesciunt ut sapiente deserunt laborum iusto? Lorem ipsum dolor sit amet consectetur adipisicing elit. Dolor provident in fugit tenetur adipisci sequi incidunt, eius eaque fuga quas ducimus magni natus dignissimos officia, quisquam asperiores ut ratione qui.</p>
        
        </section>
    );
}